run script improvements

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,9 +1,15 @@
 #!/bin/bash
+
+fatal()
+{
+	echo "$1"
+	exit 1
+}
  
 echo "Compiling shaders..."
-./compile_shaders
+./compile_shaders || fatal "Shader compilation failed!"
 echo "Done!"
-cmake -B build || exit 1 
-make -C build/ || exit 1
+cmake -B build || fatal "CMake error!"
+make -C build/ || fatal "Make error!"
 
 ./build/VulkanTesting
